##spring.datasource.url=jdbc:mysql://localhost:3306/fitness_users?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://localhost:3306/fitness_users?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=sharana
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
## Application Info
#spring.application.name=user-service
#server.port=8081
#
## Eureka Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true


#since we have created a one center conig server to main all configuration so here we include only server.application.name
spring.application.name=user-service
spring.config.import=optional:configserver:http://localhost:8888


