
#spring.application.name=activity-service

spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/activities?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.debug=false
server.port = 8082
spring.rabbitmq.host = localhost
spring.rabbitmq.username = guest
spring.rabbitmq.port = 5672
spring.rabbitmq.password = guest

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

# create a exchange with name fitness.exchange topic: topic durable :yes
# we need to specify where rabbit mq is running
#  use this to start docker image
# # latest RabbitMQ 4.x
#docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4-management
rabbitmq.exchange.name = fitness.exchange
rabbitmq.queue.name = activity.queue
rabbitmq.routing.key = activity.tracking