#spring.application.name=AI-Service
server.port =8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true


spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/fitnessrecomendation?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.debug=false




spring.rabbitmq.host = localhost
spring.rabbitmq.username = guest
spring.rabbitmq.port = 5672
spring.rabbitmq.password = guest
rabbitmq.exchange.name = fitness.exchange
rabbitmq.queue.name = activity.queue
rabbitmq.routing.key = activity.tracking

gemini.api.url = ${GEMINI_API_URL}
gemini.api.key = ${GEMINI_API_KEY}